package fantasytactics;

import java.util.*;
import java.io.*;
public class Job implements Serializable {
	String name;
	public int type;
	public int weapType;
	public int armorType;
	public int hatType;
	public int intHP;
	public int intMP;
	public int intMove;
	public int intSpd;
	public int intJmp;
	public int intEvd;
	public int intAtk;
	public int intDef;
	public int intMgc;
	public int intRes;
	public int atkBon;
	public int HpF;
	public int MpF;
	public int AtkF;
	public int DefF;
	public int MgcF;
	public int ResF;
	public ArrayList<PreReq> required;
	double SpdF;
	int level;
	int curJP;
	int totalJP;
	AbilitySet abilSet;

	Job(int typ) {
            level = 1;
            curJP = 0;
            totalJP = 0;
            type = typ;
            abilSet = new AbilitySet(typ);
            switch (typ) { // setting stats as per Job as defined in Stats
                case Stats.SOLDIER:
            	name = "Soldier";
                required = null;
		weapType = Stats.SWORDS;
		armorType = Stats.ARMOR;
		hatType = Stats.HELMETS;
		intHP = Stats.HPSOLDIER;
		intMP = Stats.MPSOLDIER;
		intMove = Stats.MVESOLDIER;
		intJmp = Stats.JMPSOLDIER;
		intSpd = Stats.SPDSOLDIER;
		intEvd = Stats.EVDSOLDIER;
		intAtk = Stats.ATKSOLDIER;
		intDef = Stats.DEFSOLDIER;
		intMgc = Stats.MGCSOLDIER;
		intRes = Stats.RESSOLDIER;
		atkBon = Stats.ABONSOLDIER;
		HpF = Stats.HPFSOLDIER;
		MpF = Stats.MPFSOLDIER;
		AtkF = Stats.ATKFSOLDIER;
		DefF = Stats.DEFFSOLDIER;
		MgcF = Stats.MGCFSOLDIER;
		ResF = Stats.RESFSOLDIER;
		SpdF = Stats.SPDFSOLDIER;
		break;
            case Stats.THIEF:
		name = "Thief";
		required = null;
		weapType = Stats.KNIVES;
                armorType = Stats.CLOTHES;
		hatType = Stats.HATS;
		intHP = Stats.HPTHIEF;
		intMP = Stats.MPTHIEF;
		intMove = Stats.MVETHIEF;
		intJmp = Stats.JMPTHIEF;
		intSpd = Stats.SPDTHIEF;
		intEvd = Stats.EVDTHIEF;
		intAtk = Stats.ATKTHIEF;
		intDef = Stats.DEFTHIEF;
		intMgc = Stats.MGCTHIEF;
		intRes = Stats.RESTHIEF;
		atkBon = Stats.ABONTHIEF;
		HpF = Stats.ATKFTHIEF;
		MpF = Stats.MPFTHIEF;
		AtkF = Stats.ATKFTHIEF;
		DefF = Stats.DEFTHIEF;
		MgcF = Stats.MGCFTHIEF;
		ResF = Stats.RESFTHIEF;
		SpdF = Stats.SPDFTHIEF;
		break;
            case Stats.HEALER:
		name = "Healer";
		required = null;
		weapType = Stats.STAVES;
		armorType = Stats.ROBES;
		hatType = Stats.HATS;
		intHP = Stats.HPHEALER;
		intMP = Stats.MPHEALER;
		intMove = Stats.MVEHEALER;
		intJmp = Stats.JMPHEALER;
		intSpd = Stats.SPDHEALER;
		intEvd = Stats.EVDHEALER;
		intAtk = Stats.ATKHEALER;
		intDef = Stats.DEFHEALER;
		intMgc = Stats.MGCHEALER;
		intRes = Stats.RESHEALER;
		atkBon = Stats.ABONHEALER;
		HpF = Stats.HPFHEALER;
		MpF = Stats.MPFHEALER;
		AtkF = Stats.ATKFHEALER;
		DefF = Stats.DEFFHEALER;
		MgcF = Stats.MGCFHEALER;
		ResF = Stats.RESFHEALER;
		SpdF = Stats.SPDFHEALER;
                break;
            case Stats.MAGE:
		name = "Mage";
                required = null;
		weapType = Stats.RODS;
		armorType = Stats.ROBES;
		hatType = Stats.HATS;
		intHP = Stats.HPMAGE;
		intMP = Stats.MPMAGE;
		intMove = Stats.MVEMAGE;
		intJmp = Stats.JMPMAGE;
		intSpd = Stats.SPDMAGE;
		intEvd = Stats.EVDMAGE;
		intAtk = Stats.ATKMAGE;
		intDef = Stats.DEFMAGE;
		intMgc = Stats.MGCMAGE;
		intRes = Stats.RESMAGE;
		atkBon = Stats.ABONMAGE;
		HpF = Stats.HPFMAGE;
		MpF = Stats.MPFMAGE;
		AtkF = Stats.ATKFMAGE;
		DefF = Stats.DEFFMAGE;
		MgcF = Stats.MGCFMAGE;
		ResF = Stats.RESFMAGE;
		SpdF = Stats.SPDFMAGE;
		break;
            case Stats.ARCHER:
		name = "Archer";
		required = null;
		weapType = Stats.BOWS;
		armorType = Stats.CLOTHES;
		hatType = Stats.HATS;
		intHP = Stats.HPARCHER;
		intMP = Stats.MPARCHER;
		intMove = Stats.MVEARCHER;
		intJmp = Stats.JMPARCHER;
		intSpd = Stats.SPDARCHER;
		intEvd = Stats.EVDARCHER;
		intAtk = Stats.ATKARCHER;
		intDef = Stats.DEFARCHER;
		intMgc = Stats.MGCARCHER;
		intRes = Stats.RESARCHER;
		atkBon = Stats.ABONARCHER;
		HpF = Stats.HPFARCHER;
		MpF = Stats.MPFARCHER;
		AtkF = Stats.ATKFARCHER;
		DefF = Stats.DEFFARCHER;
		MgcF = Stats.MGCARCHER;
		ResF = Stats.RESFARCHER;
		SpdF = Stats.SPDFARCHER;
		break;
            case Stats.FIGHTER:
		name = "Fighter";
		weapType = Stats.BLADES;
		armorType = Stats.ARMOR;
		hatType = Stats.HELMETS;
		intHP = Stats.HPFIGHTER;
		intMP = Stats.MPFIGHTER;
		required = new ArrayList<PreReq>();
		required.add(new PreReq(Stats.SOLDIER,4));
		intMove = Stats.MVEFIGHTER;
		intJmp = Stats.JMPFIGHTER;
		intSpd = Stats.SPDFIGHTER;
		intEvd = Stats.EVDFIGHTER;
		intAtk = Stats.ATKFIGHTER;
		intDef = Stats.DEFFIGHTER;
		intMgc = Stats.MGCFIGHTER;
		intRes = Stats.RESFIGHTER;
		atkBon = Stats.ABONFIGHTER;
		HpF = Stats.HPFFIGHTER;
		MpF = Stats.MPFFIGHTER;
		AtkF = Stats.ATKFFIGHTER;
		DefF = Stats.DEFFFIGHTER;
		MgcF = Stats.MGCFFIGHTER;
		ResF = Stats.RESFFIGHTER;
		SpdF = Stats.SPDFFIGHTER;
		break;
            case Stats.NINJA:
		name = "Ninja";
		weapType = Stats.KATANAS;
		armorType = Stats.CLOTHES;
		hatType = Stats.HATS;
		required = new ArrayList<PreReq>();
		required.add(new PreReq(Stats.THIEF,4));
		intHP = Stats.HPNINJA;
		intMP = Stats.MPNINJA;
		intMove = Stats.MVENINJA;
		intJmp = Stats.JMPNINJA;
		intSpd = Stats.SPDNINJA;
		intEvd = Stats.EVDNINJA;
		intAtk = Stats.ATKNINJA;
		intDef = Stats.DEFNINJA;
		intMgc = Stats.MGCNINJA;
		intRes = Stats.RESNINJA;
		atkBon = Stats.ABONNINJA;
		HpF = Stats.HPFNINJA;
		MpF = Stats.MPFNINJA;
		AtkF = Stats.ATKFNINJA;
		DefF = Stats.DEFFNINJA;
		MgcF = Stats.MGCFNINJA;
		ResF = Stats.RESFNINJA;
		SpdF = Stats.SPDFNINJA;
		break;
            case Stats.SEER:
                name = "Seer";
                required = new ArrayList<PreReq>();
		required.add(new PreReq(Stats.HEALER,4));
		weapType = Stats.BOOKS;
		armorType = Stats.ROBES;
		hatType = Stats.HELMETS;
		intHP = Stats.HPSEER;
		intMP = Stats.MPSEER;
		intMove = Stats.MVESEER;
		intJmp = Stats.JMPSEER;
		intSpd = Stats.SPDSEER;
		intEvd = Stats.EVDSEER;
		intAtk = Stats.ATKSEER;
		intDef = Stats.DEFSEER;
		intMgc = Stats.MGCSEER;
		intRes = Stats.RESSEER;
		atkBon = Stats.ABONSEER;
		HpF = Stats.HPFSEER;
		MpF = Stats.MPFSEER;
		AtkF = Stats.ATKFSEER;
		DefF = Stats.DEFFSEER;
		MgcF = Stats.MGCFSEER;
		ResF = Stats.RESFSEER;
		SpdF = Stats.SPDFSEER;
		break;
            case Stats.WIZARD:
                name = "Wizard";
		required= new ArrayList<PreReq>();
		required.add(new PreReq(Stats.MAGE, 4));
		weapType = Stats.RODS;
		armorType = Stats.ROBES;
		hatType = Stats.HATS;
		intHP = Stats.HPWIZARD;
		intMP = Stats.MPWIZARD;
		intMove = Stats.MVEWIZARD;
		intJmp = Stats.JMPWIZARD;
		intSpd = Stats.SPDWIZARD;
		intEvd = Stats.EVDWIZARD;
		intAtk = Stats.ATKWIZARD;
		intDef = Stats.DEFWIZARD;
		intMgc = Stats.MGCWIZARD;
		intRes = Stats.RESWIZARD;
		atkBon = Stats.ABONWIZARD;
		HpF = Stats.HPFWIZARD;
		MpF = Stats.MPFWIZARD;
		AtkF = Stats.ATKFWIZARD;
		DefF = Stats.DEFFWIZARD;
		MgcF = Stats.MGCFWIZARD;
		ResF = Stats.RESFWIZARD;
		SpdF = Stats.SPDFWIZARD;
		break;
            case Stats.HUNTER:
		required =new ArrayList<PreReq>();
		required.add(new PreReq(Stats.ARCHER,4));
		weapType = Stats.GREATBOWS;
		armorType = Stats.CLOTHES;
		hatType = Stats.HATS;
		intHP = Stats.HPHUNTER;
		intMP = Stats.MPHUNTER;
		intMove = Stats.MVEHUNTER;
		intJmp = Stats.JMPHUNTER;
		intSpd = Stats.SPDHUNTER;
		intEvd = Stats.EVDHUNTER;
		intAtk = Stats.ATKHUNTER;
		intDef = Stats.DEFHUNTER;
		intMgc = Stats.MGCHUNTER;
		intRes = Stats.RESHUNTER;
		atkBon = Stats.ABONHUNTER;
		HpF = Stats.HPFHUNTER;
		MpF = Stats.MPFHUNTER;
		AtkF = Stats.ATKHUNTER;
		DefF = Stats.DEFFHUNTER;
		MgcF = Stats.MGCFHUNTER;
		ResF = Stats.RESFHUNTER;
		SpdF = Stats.SPDHUNTER;
		break;		
        }
    }
	public boolean levelUp() {
		if (totalJP >= level*100) {
			level++;
			return true;
		} else {
			return false;
		}
	}
}